title: America's Bunny background
author: Sophia Corbett
email: scorb3@ocdsb.ca
theme: minima
description: > # this means to ignore newlines until "baseurl:"
 According to other accounts, the Easter bunny first arrived in 
 America in the 1700s with German settlers who settled in Pennsylvania 
 and brought their egg-laying hare known as "Osterhase" or "Oschter Haws" with them.
 Their children built nests for this species to lay its colourful eggs in.


